DATA32 @@RANDOM_ID@@
MOVE32_32(@@POWER@@, @@RANDOM_ID@@)
CALL(motors_overflow_check_EV3_KERNEL_util, @@RANDOM_ID@@, @@RANDOM_ID@@)
DATA8 @@RANDOM_ID_1@@
MOVE32_8(@@RANDOM_ID@@, @@RANDOM_ID_1@@)
OUTPUT_POWER(0, @@PORT@@, @@RANDOM_ID_1@@)
OUTPUT_START(0, @@PORT@@)
