#!/bin/bash

# Welcome to TRIK Studio! Take it, hold it, love it.

set -o errexit

cd "$(dirname "$0")"

if which python3 >/dev/null 2>&1 && [[ ! -v TRIK_PYTHONPATH ]] ; then
export TRIK_PYTHONPATH=$(python3 -c 'import os; import sys; print(os.pathsep.join(sys.path))')
fi

exec bin/trik-studio "$@"
