DATA8 @@RANDOM_ID_5@@
JR_TRUE(@@RANDOM_ID_5@@, @@RANDOM_ID_2@@)
DATA32 @@RANDOM_ID_1@@
MOVE32_32(0, @@RANDOM_ID_1@@)
MOVE8_8(1, @@RANDOM_ID_5@@)
@@RANDOM_ID_2@@:
JR_LTEQ32(@@BOUND@@, @@RANDOM_ID_1@@, @@RANDOM_ID_3@@)
ADD32(1, @@RANDOM_ID_1@@, @@RANDOM_ID_1@@)
@@BODY@@
JR(@@RANDOM_ID_2@@)
@@RANDOM_ID_3@@:
MOVE8_8(0, @@RANDOM_ID_5@@)
